apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: dcim
type: Opaque
stringData:
  username: dcim
  password: dcim
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dcim
type: Opaque
stringData:
  oidc-client-secret: dev-secret-change-me
  dnssec-secret: ""
  redis-dsn: redis://redis:6379/0
  postgres-dsn: postgresql+asyncpg://dcim:dcim@postgres:5432/dcim
