// Zone-file ingestion.
//
// Re-parses the same BIND-format zone file the operator passed to
// the parent `file` plugin block, extracts the owner-name set + per-
// owner type bitmap + opt-out delegation flags, and hands it to
// buildChain. Re-parsing instead of reading the live `file` zone
// tree is a deliberate coupling tradeoff (see README "Layout" and
// the build-out plan): we trade a small duplicate parse cost for
// zero dependency on CoreDNS's unexported zone-tree types.
//
// `miekg/dns.ZoneParser` is the same parser the upstream `file`
// plugin uses internally, so we get bit-identical parsing without
// reaching into any private API.

package nsec3sign

import (
	"errors"
	"fmt"
	"os"

	"github.com/miekg/dns"
)

// loadChain parses the configured zone file and builds the NSEC3
// chain in-place on the plugin. No-op when no zone file is
// configured — operators who only want RRSIG signing (without
// denial proofs) can skip the `zone file` directive.
func (n *Nsec3Sign) loadChain() error {
	if n.ZoneFile == "" {
		return nil
	}
	names, apex, err := parseZoneFile(n.ZoneFile)
	if err != nil {
		return fmt.Errorf("nsec3sign: zone file %s: %w", n.ZoneFile, err)
	}
	n.Chain = buildChain(apex, n.Salt, n.Iterations, n.OptOut, names)
	chainEntries.WithLabelValues(apex).Set(float64(len(n.Chain.nodes)))
	log.Infof("nsec3sign: chain built for %s with %d owner names", apex, len(names))
	return nil
}

// parseZoneFile reads a BIND-format zone file and returns the
// owner-name + type list ready for buildChain, plus the apex
// detected from the SOA record's owner.
//
// `$INCLUDE` is disabled — letting a zone file pull in other paths
// from disk is a footgun for a network-loaded config surface (DCIM
// renders these from the central API), and BIND zones generated by
// renderers never use it.
func parseZoneFile(path string) ([]nameInfo, string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, "", fmt.Errorf("open: %w", err)
	}
	defer f.Close()

	// Empty origin forces the parser to use $ORIGIN from the file.
	// Every BIND-format zone DCIM renders starts with $ORIGIN, so
	// this is the right default; if it's missing the parser will
	// report a clear error on the first unqualified name.
	zp := dns.NewZoneParser(f, "", path)
	zp.SetIncludeAllowed(false)

	owners, apex := collectOwners(zp)
	if err := zp.Err(); err != nil {
		return nil, "", fmt.Errorf("parse: %w", err)
	}
	if apex == "" {
		return nil, "", errors.New("no SOA record found")
	}

	return ownersToNameInfo(owners, apex), apex, nil
}

// ownerState aggregates information about one owner name as we walk
// the zone. The boolean flags drive opt-out detection at the end.
type ownerState struct {
	types map[uint16]struct{}
	hasNS bool
	hasDS bool
}

// collectOwners walks the parser and bins RRs by owner. Returns the
// per-owner state plus the detected apex (owner of the first SOA).
func collectOwners(zp *dns.ZoneParser) (map[string]*ownerState, string) {
	owners := make(map[string]*ownerState)
	var apex string

	for rr, ok := zp.Next(); ok; rr, ok = zp.Next() {
		h := rr.Header()
		owner := dns.CanonicalName(h.Name)

		// First SOA wins. Subsequent SOAs (which shouldn't exist in
		// a well-formed file) get treated as data at the apex.
		if h.Rrtype == dns.TypeSOA && apex == "" {
			apex = owner
		}

		os, ok := owners[owner]
		if !ok {
			os = &ownerState{types: make(map[uint16]struct{})}
			owners[owner] = os
		}
		os.types[h.Rrtype] = struct{}{}
		switch h.Rrtype {
		case dns.TypeNS:
			os.hasNS = true
		case dns.TypeDS:
			os.hasDS = true
		}
	}
	return owners, apex
}

// ownersToNameInfo converts the collected per-owner state into the
// flat slice buildChain consumes. Each owner contributes one
// nameInfo; RRSIG is added to the type bitmap unconditionally
// because the signer attaches one per RRset, so every owner with
// records will end up with RRSIGs at runtime.
//
// Opt-out detection: any name that has NS records but no DS, and is
// not the apex itself, is an insecure delegation per RFC 5155 §6.
// buildChain elides those from the chain when the plugin's OptOut
// flag is set.
func ownersToNameInfo(owners map[string]*ownerState, apex string) []nameInfo {
	out := make([]nameInfo, 0, len(owners))
	for owner, os := range owners {
		types := make([]uint16, 0, len(os.types)+1)
		for t := range os.types {
			types = append(types, t)
		}
		// We always sign RRsets at this owner, so the NSEC3's type
		// bitmap should advertise RRSIG for it. Validators check
		// the bitmap when they receive an NSEC3 for the owner, and
		// a missing RRSIG bit on a name that's actually signed
		// would look like a misconfigured zone.
		types = append(types, dns.TypeRRSIG)
		out = append(out, nameInfo{
			Name:     owner,
			Types:    types,
			OptedOut: os.hasNS && !os.hasDS && owner != apex,
		})
	}
	return out
}
