"""Alembic include_object filter — kept out of env.py so it can be
imported and unit-tested without alembic's runtime context.

The LIR module is Go-native (see docs/lir.md). The phase-1 cleanup
commit (fdd18d0) deleted models/lir.py because there are no Python
ORM consumers — the API and seed paths write via raw text() SQL
against the otter-go-owned schema. Migration 20260528_0065 still
creates and owns the three LIR tables; we just don't carry SQLAlchemy
models for them.

Without this filter, `alembic revision --autogenerate` would compare
the live DB to Base.metadata, see lir_pools/lir_requests/
lir_allocations as 'in DB but not in metadata,' and emit
op.drop_table(...) for each — silent data loss on the next apply.
The filter tells autogenerate to skip those tables and all of their
child objects (columns, indexes, constraints) so an unrelated
schema tweak elsewhere in dcim/models/ can be autogenerated without
collateral damage.
"""

from __future__ import annotations

# The three tables migration 0065 owns. If a future migration adds
# another LIR-Go-owned table, append its name here.
LIR_TABLES = frozenset({"lir_pools", "lir_requests", "lir_allocations"})


def include_object(obj, name: str, type_: str, _reflected: bool, _compare_to) -> bool:
    """Return False to exclude `obj` from alembic autogenerate, True
    to keep it under normal comparison.

    Skips:
      * top-level Table entries whose name is in LIR_TABLES
      * child objects (columns, indexes, FK/unique/check constraints)
        whose parent .table.name is in LIR_TABLES

    Everything else passes through unchanged.
    """
    if type_ == "table" and name in LIR_TABLES:
        return False
    # Child objects carry their parent Table reference via .table.
    parent = getattr(obj, "table", None)
    parent_name = getattr(parent, "name", None) if parent is not None else None
    return parent_name not in LIR_TABLES
