apiVersion: v1
kind: Service
metadata:
  name: hickory
  namespace: dcim-site42
spec:
  selector:
    app: site42
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: doh
      port: 443
      targetPort: 443
      protocol: TCP
    - name: dot
      port: 853
      targetPort: 853
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-auth
  namespace: dcim-site42
spec:
  selector:
    app: site42
  ports:
    - name: dns-tcp
      port: 15353
      targetPort: 15353
      protocol: TCP
    - name: metrics
      port: 9153
      targetPort: 9153
      protocol: TCP
  type: ClusterIP
