apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcim.fullname" . }}-frontend
  labels:
    {{- include "dcim.labels" . | nindent 4 }}
    app.kubernetes.io/component: finch
spec:
  replicas: {{ .Values.finch.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: finch
  template:
    metadata:
      labels:
        {{- include "dcim.labels" . | nindent 8 }}
        app.kubernetes.io/component: finch
    spec:
      containers:
        - name: finch
          image: {{ include "dcim.image" (dict "Values" .Values "name" "finch") }}
          ports:
            - { name: http, containerPort: 80 }
          resources:
            {{- toYaml .Values.finch.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcim.fullname" . }}-frontend
spec:
  type: {{ .Values.finch.service.type }}
  ports:
    - port: {{ .Values.finch.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: finch
