{{- if .Values.migrations.runOnInstall }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dcim.fullname" . }}-migrate-{{ .Release.Revision }}
  labels:
    {{- include "dcim.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alembic
          image: {{ include "dcim.image" (dict "Values" .Values "name" "otter") }}
          command: ["alembic", "upgrade", "head"]
          env:
            - { name: DCIM_POSTGRES_DSN, value: {{ .Values.postgresql.dsn | quote }} }
{{- end }}
