apiVersion: v1
kind: Secret
metadata:
  name: dcim-secrets
  labels: {{- include "dcim.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_secret: {{ .Values.config.jwtSecret | quote }}
  collector_token_secret: {{ .Values.config.collectorTokenSecret | quote }}
