apiVersion: v1
kind: Secret
metadata:
  name: dcim-secrets
  labels: {{- include "dcim.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_secret: {{ .Values.global.config.jwtSecret | quote }}
  collector_token_secret: {{ .Values.global.config.collectorTokenSecret | quote }}
  {{- with .Values.global.config.regiondeploy }}
  regiondeploy_callback_secret: {{ .callbackSecret | quote }}
  {{- end }}
