apiVersion: v1
kind: Secret
metadata:
  name: dcim-secrets
  labels: {{- include "dcim.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_secret: {{ .Values.global.config.jwtSecret | quote }}
  {{- with .Values.global.config.jwtOldSecrets }}
  jwt_old_secrets: {{ . | quote }}
  {{- end }}
  collector_token_secret: {{ .Values.global.config.collectorTokenSecret | quote }}
  {{- with .Values.global.config.oidc.clientSecret }}
  oidc_client_secret: {{ . | quote }}
  {{- end }}
  {{- with .Values.global.config.dnssecSecret }}
  dnssec_secret: {{ . | quote }}
  {{- end }}
