"""SQLAlchemy ORM models. Import here so Alembic autogenerate sees them."""

from .alerts import Alert, AlertRule, MaintenanceWindow
from .audit import AuditLog
from .auth import ApiToken, Permission, Role, RoleScope, User, UserRole
from .collectors import Collector, CollectorHeartbeat
from .dns import (
    AnycastBgpBinding,
    AnycastGroup,
    AnycastService,
    BgpPeer,
    DnsRecord,
    DnsRecordSource,
    DnsRecordType,
    DnsServer,
    DnsServerRole,
    DnsZone,
    DnsZoneKind,
)
from .inventory import (
    Asset,
    AssetFace,
    AssetMount,
    Building,
    Cable,
    Circuit,
    PduSide,
    PowerFeed,
    Rack,
    Region,
    Room,
    Row,
    Site,
    SiteGroup,
    SiteGroupMembership,
)
from .ipam import (
    BgpAddressFamily,
    DhcpServer,
    Fabric,
    IPAddress,
    IpAddressRole,
    IpAddressSource,
    IpAddressStatus,
    Overlay,
    OverlayKind,
    Subnet,
    Supernet,
    Vni,
    VniKind,
    Vrf,
    VrfBgpPeer,
    Vtep,
    VtepRole,
    VtepVniMembership,
)
from .notifications import ChannelKind, NotificationChannel
from .power import Outlet, PowerConnection
from .telemetry_meta import TelemetrySource

__all__ = [
    "Alert",
    "AlertRule",
    "AnycastBgpBinding",
    "AnycastGroup",
    "AnycastService",
    "ApiToken",
    "Asset",
    "AssetFace",
    "AssetMount",
    "AuditLog",
    "BgpAddressFamily",
    "BgpPeer",
    "Building",
    "Cable",
    "ChannelKind",
    "Circuit",
    "Collector",
    "CollectorHeartbeat",
    "DhcpServer",
    "DnsRecord",
    "DnsRecordSource",
    "DnsRecordType",
    "DnsServer",
    "DnsServerRole",
    "DnsZone",
    "DnsZoneKind",
    "Fabric",
    "IPAddress",
    "IpAddressRole",
    "IpAddressSource",
    "IpAddressStatus",
    "MaintenanceWindow",
    "NotificationChannel",
    "Outlet",
    "Overlay",
    "OverlayKind",
    "PduSide",
    "Permission",
    "PowerConnection",
    "PowerFeed",
    "Rack",
    "Region",
    "Role",
    "RoleScope",
    "Room",
    "Row",
    "Site",
    "SiteGroup",
    "SiteGroupMembership",
    "Subnet",
    "Supernet",
    "TelemetrySource",
    "User",
    "UserRole",
    "Vni",
    "VniKind",
    "Vrf",
    "VrfBgpPeer",
    "Vtep",
    "VtepRole",
    "VtepVniMembership",
]
