// PR 82 — BIND zone-file parser.
//
// Ports services.dns.parse_bind_zone using github.com/miekg/dns
// (the same library CoreDNS uses internally). Output shape
// matches the Python parser:
//
//	{
//	  "zone_name": "prod.dcim.mil.",
//	  "soa": {"mname": ..., "rname": ..., "refresh": ..., ...},
//	  "default_ttl": 300,
//	  "records": [{"name": "leaf-01", "type": "A", ...}, ...],
//	  "warnings": ["skipped DNSKEY at apex", ...],
//	}
//
// Unsupported record types and directives ($INCLUDE, $GENERATE)
// become warnings; structural errors (missing SOA, malformed
// rdata) return ErrBindImport.
package dns

import (
	"errors"
	"fmt"
	"strings"

	"github.com/miekg/dns"
)

// ErrBindImport is returned for parse failures that the operator
// must fix (missing SOA, syntax errors) — distinct from per-row
// warnings which are recoverable skips.
var ErrBindImport = errors.New("bind import error")

// supportedImportTypes mirrors _SUPPORTED_IMPORT_TYPES from
// services.dns. DNSSEC-related types (DNSKEY/RRSIG/NSEC*) are
// intentionally excluded; they're regenerated by the renderer
// from key material, not imported.
var supportedImportTypes = map[string]struct{}{
	"A": {}, "AAAA": {}, "CNAME": {}, "MX": {}, "TXT": {},
	"SRV": {}, "NS": {}, "CAA": {}, "PTR": {},
}

// bindParsedRecord is the normalized output shape per non-SOA RR.
type bindParsedRecord struct {
	Name string         `json:"name"`
	Type string         `json:"type"`
	TTL  *int32         `json:"ttl"`
	Data map[string]any `json:"data"`
}

// bindParsedSoa carries the SOA fields the importer wants to apply
// when update_soa=true. Same shape as the Python _bind_soa_payload.
type bindParsedSoa struct {
	Mname   string `json:"mname"`
	Rname   string `json:"rname"`
	Refresh int32  `json:"refresh"`
	Retry   int32  `json:"retry"`
	Expire  int32  `json:"expire"`
	Minimum int32  `json:"minimum"`
}

// bindParsed is the full parser output. Empty fields are fine
// (zone_name may be "" if origin couldn't be inferred; SOA is
// always non-nil since missing SOA raises ErrBindImport).
type bindParsed struct {
	ZoneName   string             `json:"zone_name"`
	Soa        bindParsedSoa      `json:"soa"`
	DefaultTTL int32              `json:"default_ttl"`
	Records    []bindParsedRecord `json:"records"`
	Warnings   []string           `json:"warnings"`
}

// labelFor turns a fully-qualified owner name into the bare label
// DnsRecord stores ("@" at apex, otherwise the label relative to
// origin). Matches services.dns._bind_label_for.
func labelFor(name, origin string) string {
	name = strings.TrimSuffix(name, ".")
	origin = strings.TrimSuffix(origin, ".")
	if origin != "" && (name == origin || name == "") {
		return "@"
	}
	if origin != "" && strings.HasSuffix(name, "."+origin) {
		return strings.TrimSuffix(name, "."+origin)
	}
	return name
}

// stripFinalDot trims a single trailing dot — used for hostnames
// embedded in MX/SRV/CNAME rdata where the Python codebase stores
// them without the canonical dot.
func stripFinalDot(s string) string {
	return strings.TrimSuffix(s, ".")
}

// rdataToRecordData translates one miekg/dns RR into the JSON
// shape DnsRecord.data uses. Returns (data, ok). When ok=false,
// the caller emits a "skipped malformed" warning.
//
//nolint:gocyclo // type-discriminated dispatch, matches Python shape
func rdataToRecordData(rr dns.RR) (map[string]any, bool) {
	switch r := rr.(type) {
	case *dns.A:
		return map[string]any{"target": r.A.String()}, true
	case *dns.AAAA:
		return map[string]any{"target": r.AAAA.String()}, true
	case *dns.CNAME:
		return map[string]any{"target": stripFinalDot(r.Target)}, true
	case *dns.NS:
		return map[string]any{"target": stripFinalDot(r.Ns)}, true
	case *dns.PTR:
		return map[string]any{"target": stripFinalDot(r.Ptr)}, true
	case *dns.MX:
		return map[string]any{
			"priority": int(r.Preference),
			"target":   stripFinalDot(r.Mx),
		}, true
	case *dns.TXT:
		// miekg stores TXT as []string segments; the Python parser
		// joins them into one logical string (matches RFC 1035
		// behavior for multi-segment TXT records).
		return map[string]any{"text": strings.Join(r.Txt, "")}, true
	case *dns.SRV:
		return map[string]any{
			"priority": int(r.Priority),
			"weight":   int(r.Weight),
			"port":     int(r.Port),
			"target":   stripFinalDot(r.Target),
		}, true
	case *dns.CAA:
		return map[string]any{
			"flags": int(r.Flag),
			"tag":   r.Tag,
			"value": r.Value,
		}, true
	}
	return nil, false
}

// soaFromRR pulls SOA fields into the parsed payload. Returns ok
// false if the RR isn't an SOA (defensive — caller branches on
// type before reaching here).
func soaFromRR(rr *dns.SOA) bindParsedSoa {
	return bindParsedSoa{
		Mname:   stripFinalDot(rr.Ns),
		Rname:   stripFinalDot(rr.Mbox),
		Refresh: int32(rr.Refresh),
		Retry:   int32(rr.Retry),
		Expire:  int32(rr.Expire),
		Minimum: int32(rr.Minttl),
	}
}

// parseBindZone consumes a BIND zone-file text blob and returns
// the normalized payload. defaultZone is appended to origin-less
// names — typically passed as `zone.name + "."` from the API.
func parseBindZone(text, defaultZone string) (*bindParsed, error) {
	out := &bindParsed{Warnings: []string{}, Records: []bindParsedRecord{}}
	out.ZoneName = defaultZone

	zp := dns.NewZoneParser(strings.NewReader(text), defaultZone, "")
	zp.SetIncludeAllowed(false) // $INCLUDE is unsupported — warning, not fatal

	gotSOA := false
	for rr, ok := zp.Next(); ok; rr, ok = zp.Next() {
		hdr := rr.Header()
		rtype := dns.TypeToString[hdr.Rrtype]
		// SOA goes into the soa payload; only the first one counts
		// (miekg won't emit multiple anyway).
		if soa, isSOA := rr.(*dns.SOA); isSOA {
			out.Soa = soaFromRR(soa)
			if out.DefaultTTL == 0 {
				out.DefaultTTL = int32(soa.Minttl)
			}
			gotSOA = true
			continue
		}
		if _, supported := supportedImportTypes[rtype]; !supported {
			out.Warnings = append(out.Warnings,
				fmt.Sprintf("skipped unsupported type %s for %s",
					rtype, stripFinalDot(hdr.Name)))
			continue
		}
		data, ok := rdataToRecordData(rr)
		if !ok {
			out.Warnings = append(out.Warnings,
				fmt.Sprintf("skipped malformed %s record for %s",
					rtype, stripFinalDot(hdr.Name)))
			continue
		}
		label := labelFor(hdr.Name, defaultZone)
		var ttlPtr *int32
		if hdr.Ttl != 0 {
			t := int32(hdr.Ttl)
			ttlPtr = &t
		}
		out.Records = append(out.Records, bindParsedRecord{
			Name: label, Type: rtype, TTL: ttlPtr, Data: data,
		})
	}
	if err := zp.Err(); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrBindImport, err)
	}
	if !gotSOA {
		return nil, fmt.Errorf("%w: zone has no SOA record", ErrBindImport)
	}
	if out.DefaultTTL == 0 {
		out.DefaultTTL = 60 // matches Python's `default_ttl or 60` fallback
	}
	return out, nil
}
