// Hickory DNS recursive config renderer (PR 34 — recursive bundle
// 2/N). Pure function: no DB, no I/O. Counterpart to
// RenderCorefileRecursive — same logical inputs, different output
// format (TOML instead of CoreDNS Corefile).
//
// Mirrors Python's render_hickory_recursive_config at
// services/dns.py L1327. Coverage:
//   - One Forward (External + forward store) zone per fabric apex
//     pointing at the local auth pod.
//   - One Forward zone per operator-configured conditional forwarder.
//   - Catch-all root zone forwarding to the configured upstreams.
//   - One Primary zone per RPZ blocklist; the [[response_policy]]
//     block at the end lists them in priority order so Hickory
//     (when its response-policy plugin is enabled) applies them
//     before forwarding.
//
// Hickory expects newline-terminated TOML; the renderer produces
// deterministic output (sorted apex names, conditional forwarders,
// and RPZ zones) so the bundle etag is stable across runs.
//
// Settings-gated features (TLS / DoH / prometheus exporter / strict
// allow-networks) accept their flags as struct fields rather than
// reading from settings — keeps the renderer pure-of-environment.
package dns

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// HickoryRecursiveInput bundles render_hickory_recursive_config's args.
type HickoryRecursiveInput struct {
	FabricApexes          []string
	AuthUnicastIP         *string
	UpstreamResolvers     []string
	ConditionalForwarders []ConditionalForwarder
	RpzZoneRefs           []RPZRef
	DenyNetworks          []string
	AllowNetworks         []string

	// Optional listener/feature flags. The caller threads
	// settings/env-derived values; the renderer stays pure.
	PrometheusListenAddr    string // empty disables emission
	TLSCertPath             string
	TLSKeyPath              string
	DoTEnabled              bool
	DoHEnabled              bool
	TLSListenPort           int32
	HTTPSListenPort         int32
	DoHPath                 string
	AllowNetworksStrict     bool
}

const (
	hickoryZoneHeader        = "[[zones]]"
	hickoryForwardZoneType   = `zone_type = "External"`
	hickoryForwardZoneStores = "[zones.stores]"
	hickoryForwardStoreType  = `type = "forward"`
)

// RenderHickoryRecursiveConfig emits the Hickory recursive TOML
// config text.
func RenderHickoryRecursiveConfig(in HickoryRecursiveInput) string {
	upstreams := in.UpstreamResolvers
	if len(upstreams) == 0 {
		upstreams = []string{"1.1.1.1", "8.8.8.8"}
	}

	var lines []string
	lines = append(lines,
		"# Generated by DCIM — do not hand-edit. Re-render via",
		"# /api/v1/dns/servers/{id}/bundle.",
		"",
		`listen_addrs_ipv4 = ["0.0.0.0"]`,
		`listen_addrs_ipv6 = ["::"]`,
		"listen_port = 53",
		"tcp_request_timeout = 5",
		"",
	)

	// Prometheus exporter line — only when the operator has opted
	// in. Mirrors Python's env-gated emission; the renderer takes
	// the resolved address string from the caller.
	if in.PrometheusListenAddr != "" {
		lines = append(lines,
			fmt.Sprintf(`prometheus_listen_addr = "%s"`, in.PrometheusListenAddr),
			"",
		)
	}

	// ACL lines BEFORE [tls_cert] — TOML tables consume every
	// following field, so deny/allow at top-level must land first.
	lines = append(lines, hickoryAclLines(in.DenyNetworks, in.AllowNetworks, in.AllowNetworksStrict)...)
	lines = append(lines, hickoryTLSLines(in)...)

	// Apex stub forwards: one Forward zone per fabric apex routed
	// to the local auth pod. Dedup + sort.
	if in.AuthUnicastIP != nil && *in.AuthUnicastIP != "" {
		for _, apex := range dedupSorted(in.FabricApexes) {
			lines = append(lines,
				hickoryForwardZone(apex, []hickoryUpstream{{Host: *in.AuthUnicastIP, Port: 53}})...,
			)
		}
	}

	// Operator conditional forwarders.
	cfs := append([]ConditionalForwarder(nil), in.ConditionalForwarders...)
	sort.SliceStable(cfs, func(i, j int) bool { return cfs[i].Pattern < cfs[j].Pattern })
	for _, cf := range cfs {
		if len(cf.Upstreams) == 0 {
			continue
		}
		ups := make([]hickoryUpstream, 0, len(cf.Upstreams))
		for _, u := range cf.Upstreams {
			h, p := splitHostPort(u, 53)
			ups = append(ups, hickoryUpstream{Host: h, Port: p})
		}
		lines = append(lines, hickoryForwardZone(cf.Pattern, ups)...)
	}

	// RPZ blocklists rendered as Primary zones, sorted by zone name.
	rpzList := append([]RPZRef(nil), in.RpzZoneRefs...)
	sort.SliceStable(rpzList, func(i, j int) bool { return rpzList[i].Name < rpzList[j].Name })
	for _, ref := range rpzList {
		lines = append(lines, hickoryPrimaryZone(ref.Name, ref.Filename)...)
	}
	if len(rpzList) > 0 {
		lines = append(lines, "[[response_policy]]")
		quoted := make([]string, 0, len(rpzList))
		for _, ref := range rpzList {
			label := strings.TrimRight(ref.Name, ".") + "."
			quoted = append(quoted, fmt.Sprintf(`"%s"`, label))
		}
		lines = append(lines, "zones = ["+strings.Join(quoted, ", ")+"]", "")
	}

	// Catch-all root zone forwarding to upstreams.
	catchUps := make([]hickoryUpstream, 0, len(upstreams))
	for _, u := range upstreams {
		h, p := splitHostPort(u, 53)
		catchUps = append(catchUps, hickoryUpstream{Host: h, Port: p})
	}
	lines = append(lines, hickoryForwardZone(".", catchUps)...)

	return strings.Join(lines, "\n")
}

type hickoryUpstream struct {
	Host string
	Port int
}

// hickoryAclLines mirrors Python's _hickory_acl_lines. Empty lists
// emit nothing — null vs empty needs an explicit operator intent;
// `allow_networks = []` rendered into TOML would lock everyone out.
func hickoryAclLines(deny, allow []string, strict bool) []string {
	denyList := uniqueSorted(deny)
	allowList := uniqueSorted(allow)
	if len(denyList) == 0 && len(allowList) == 0 {
		return nil
	}
	var lines []string
	if len(denyList) > 0 {
		lines = append(lines, "deny_networks = ["+joinQuoted(denyList)+"]")
	}
	if len(allowList) > 0 {
		lines = append(lines, "allow_networks = ["+joinQuoted(allowList)+"]")
	}
	if len(allowList) > 0 && strict {
		lines = append(lines, "allow_networks_strict = true")
	}
	lines = append(lines, "")
	return lines
}

// hickoryTLSLines mirrors Python's _hickory_tls_lines.
func hickoryTLSLines(in HickoryRecursiveInput) []string {
	if in.TLSCertPath == "" || in.TLSKeyPath == "" || (!in.DoTEnabled && !in.DoHEnabled) {
		return nil
	}
	var lines []string
	if in.DoTEnabled {
		lines = append(lines, fmt.Sprintf("tls_listen_port = %d", in.TLSListenPort))
	}
	if in.DoHEnabled {
		lines = append(lines,
			fmt.Sprintf("https_listen_port = %d", in.HTTPSListenPort),
			fmt.Sprintf(`http_endpoint = "%s"`, in.DoHPath),
		)
	}
	lines = append(lines,
		"",
		"[tls_cert]",
		fmt.Sprintf(`path = "%s"`, in.TLSCertPath),
		fmt.Sprintf(`private_key = "%s"`, in.TLSKeyPath),
		"",
	)
	return lines
}

func hickoryForwardZone(zone string, upstreams []hickoryUpstream) []string {
	zoneLabel := zone
	if zone != "." {
		zoneLabel = strings.TrimRight(zone, ".") + "."
	}
	lines := []string{
		hickoryZoneHeader,
		fmt.Sprintf(`zone = "%s"`, zoneLabel),
		hickoryForwardZoneType,
		"",
		hickoryForwardZoneStores,
		hickoryForwardStoreType,
		"",
	}
	for _, u := range upstreams {
		lines = append(lines, hickoryNsEntry(u.Host, u.Port)...)
	}
	return lines
}

func hickoryPrimaryZone(zoneName, filePath string) []string {
	zoneLabel := strings.TrimRight(zoneName, ".") + "."
	return []string{
		hickoryZoneHeader,
		fmt.Sprintf(`zone = "%s"`, zoneLabel),
		`zone_type = "Primary"`,
		"[zones.stores]",
		`type = "file"`,
		fmt.Sprintf(`file = "%s"`, filePath),
		"",
	}
}

func hickoryNsEntry(host string, port int) []string {
	return []string{
		"[[zones.stores.name_servers]]",
		fmt.Sprintf(`ip = "%s"`, host),
		"connections = [",
		fmt.Sprintf(`    { port = %d, protocol = { type = "udp" } },`, port),
		fmt.Sprintf(`    { port = %d, protocol = { type = "tcp" } },`, port),
		"]",
		"",
	}
}

// splitHostPort parses `ip` or `ip:port`. IPv6 literals carry the
// `[::1]:5353` bracket form on input; the brackets are stripped so
// the output host is always a bare IP suitable for Hickory's `ip =
// "..."` field. Mirrors Python's _split_host_port.
func splitHostPort(target string, defaultPort int) (string, int) {
	if strings.HasPrefix(target, "[") {
		end := strings.IndexByte(target, ']')
		if end < 0 {
			return target, defaultPort
		}
		host := target[1:end]
		rest := target[end+1:]
		if strings.HasPrefix(rest, ":") {
			if p, err := strconv.Atoi(rest[1:]); err == nil {
				return host, p
			}
			return host, defaultPort
		}
		return host, defaultPort
	}
	if i := strings.IndexByte(target, ':'); i >= 0 && strings.Count(target, ":") == 1 {
		host := target[:i]
		if p, err := strconv.Atoi(target[i+1:]); err == nil {
			return host, p
		}
		return target, defaultPort
	}
	return target, defaultPort
}

func uniqueSorted(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	for _, s := range in {
		seen[s] = struct{}{}
	}
	out := make([]string, 0, len(seen))
	for s := range seen {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

func joinQuoted(in []string) string {
	parts := make([]string, len(in))
	for i, s := range in {
		parts[i] = fmt.Sprintf(`"%s"`, s)
	}
	return strings.Join(parts, ", ")
}
